set search_path to conference;
select * from conferenza;
select * from ente order by id_ente;
select * from ente_conferenza ec ;
select * from sede;
select * from sala;
select * from sala where id_sede=1;
call add_conferenza('Conferenza del miele', '2023-06-30 12:00', '2023-07-01 12:00', 1, 'Apicolture e conservazione del miele', 'INFS,INU,INEA,ANPA');
call add_sessione('Miele che bontà', '2023-06-30 12:00', '2023-06-30 15:00', 1, 2); 
call add_evento('Gita',5,'1 hour');
call add_evento('Costruzione dei favi',5, '0.5 hour');
call add_intervento('L''importanza delle api nella società moderna', 'Si espone il ruolo degli insetti impollinatori','SPK2279', '5','45 minutes');
call add_intervallo('pranzo', 5, '30 minutes'); 
call add_evento('Degustazione', 5, '15 minutes'); 
select * from evento e ;
select * from speaker s ;
select * from programma p ;
select * from show_programma(5); 
select * from sessione s where id_conferenza =2;
select max(fine) from show_programma(5);
select * from sessioni;