set search_path to conference;
select * from conferenza;
select * from ente order by id_ente;
select * from ente_conferenza ec ;
select * from sede;
select * from sessione;
select * from programma p ;
select * from sala;
select * from speaker s ;
select * from sala where id_sede=1;
call add_conferenza('Conferenza del miele', '2023-06-30 12:00', '2023-07-01 12:00', 1, 'Apicolture e conservazione del miele', 'INFS,INU,INEA,ANPA');
call add_sessione('Miele che bontà', '2023-06-30 12:00', '2023-06-30 15:00', 1, 1); 
call add_evento('Gita',1,'1 hour');
call add_evento('Costruzione dei favi',1, '0.5 hour');
call add_intervento('L''importanza delle api nella società moderna', 'Si espone il ruolo degli insetti impollinatori','SPK0001', 1,'45 minutes');
call add_intervallo('pranzo', 1, '30 minutes'); 
call add_evento('Degustazione', 1, '15 minutes'); 
select * from show_programma(1); 
call add_sessione('Il fenomeno della sciamatura','2023-7-1 12:00','2023-07-01 15:00',2,1);
call add_intervento('Cosa è la sciamatura','Cosa genera il fenomeno della sciamatura','SPK0002',3, '30 minutes');
call add_intervento('Come gestire la sciamatura', 'Come affrontare la sciamatura delle api','SPK0003' ,3, '30 minutes');
select * from show_programma(3); 