--Popolamento della tabella ente
SET search_path TO conference;
insert into ente (nome,sigla) values
('Agenzia Spaziale Italiana','ASI'),
('Consiglio Nazionale delle RIcerche','CNR'),
('Istituto Nazionale di Ricerca Metrologica','INRIM'),
('Istituto Nazionale di Alta Matematica','INDAM'),
('Istituto Nazionale di Astrofisica','INAF'),
('Istituto Nazionale di Fisica Nucleare','INFN'),
('Istituto Nazionale di Geofisica e Vulcanologia','INGV'),
('Istituto Nazionale di Oceanografia e di Geofisica Sperimentale','OGS'),
('Istituto Italiano di Studi Germanici','IISG'),
('Istituto Italiano di Studi Orientali','ISO'),
('Istituto Italiano per gli Studi Filosofici','IISF'),
('Istituto Italiano per gli Studi Storici','IISS'),
('Consorzio per l''Area di Ricerca Scientifica e Tecnologia di Trieste','ASP'),
('Istituto Nazionale di Ottica','INO'),
('Istituto Nazionale per la Fauna Selvatica','INFS'),
('Istituto Nazionale di Statistica','ISTAT'),
('Istituto Nazionale di Urbanistica','INU'),
('Istituto Nazionale per la Valutazione del Sistema Educativo di Istruzione e di Formazione','INVALSI'),
('Istituto Nazionale Economia Agraria','INEA'),
('Comitato Nazionale per l''Energia Nucleare','CNEN'),
('Istituto di Studi per la Programmazione Economica','ISPE'),
('Istituto Elettrotecnico Nazionale Galileo Ferraris','IEN'),
('Istituto Superiore di Sanità','ISS'),
('Agenzia Nazionale per la Protezione Ambientale','ANPA'),
('Istituto Nazionale per la Fisica della Materia','INFM'),
('Centro Interforze Studi per le Applicazioni Militari','CISAM');
