INSERT INTO indirizzo (via, civico, cap, city, provincia, nazione) values
('Via del Corso','123','00186','Roma','RM','Italia'),
('Strada Statale Sempione', '28', '20017', 'Rho','MI','Italia'),
('Piazza Santa Croce', '16', '50122', 'Firenze','FI','Italia'),
('Viale della Fiera', '20', '44124', 'Ferrara','FE','Italia'),
('Via Partenope', '1', '80121', 'Napoli','NA','Italia'),
('Piazza Maggiore', '6', '40124', 'Bologna','BO','Italia'),
('Via Roma', '156', '10122', 'Torino','TO','Italia'),
('Piazza San Marco', '1', '30124', 'Venezia','VE','Italia'),
('Corso Porta Nuova', '1', '37122', 'Verona','VR','Italia'),
('Via Vittorio Emanuele', '121', '95131', 'Catania','CT','Italia'),
('Via XX Settembre', '20', '16121', 'Genova','GE','Italia'),
('Via Roma', '139', '90133', 'Palermo','PA','Italia'),
('Via Maqueda', '187', '90133', 'Palermo','PA','Italia'),
('Via Emilia', '155', '47923', 'Rimini','RN','Italia'),
('Via Sparano', '120', '70121', 'Bari','BA','Italia'),
('Piazza Unità d''Italia', '1', '34121', 'Trieste','TS','Italia'),
('Viale Trieste', '105', '09123', 'Cagliari','CA','Italia'),
('Via Festa del Perdono', '7', '20122', 'Milano','MI','Italia'),
('Piazzale Aldo Moro', '5', '00185', 'Roma','RM','Italia'),
('Largo Luchino Visconti', '4', '22012', 'Cernobbio','CO','Italia'),
('Via Pasitea', '346', '84017', 'Positano','SA','Italia'),
('Viale Pietro de Coubertin', '30', '00196', 'Roma','RM','Italia'),
('Piazza Mafalda di Savoia', '10098', '10098', 'Rivoli','TO','Italia'),
('Via Trionfale', '151', '00136', 'Roma','RM','Italia'),
('Via Zamboni', '33', '40126', 'Bologna','BO','Italia'),
('Via della Lungara', '230', '00165', 'Roma','RM','Italia'),
('Via Nazionale', '194', '00184', 'Roma','RM','Italia'),
('Via Frascati', '51', '00040', 'Monte Porzio Catone','RM','Italia'),
('Via VIII Febbraio', '2', '35122', 'Padova','PD','Italia'),
('Via Bolognese', '120', '50139', 'Firenze','FI','Italia'),
('Isola di San Giorgio Maggiore', '30124', '30124', 'Venezia','VE','Italia'),
('Piazza Castello', '2', '27011', 'Belgioioso','PV','Italia');



INSERT INTO sede (nome,indirizzo) VALUES
('Centro Congressi Roma', 1),
('Fiera Milano Congressi', 2),
('Centro Congressi Firenze', 3),
('Palazzo dei Congressi', 4),
('Centro Congressi Napoli', 5),
('Centro Congressi Bologna',6 ),
('Centro Congressi Torino', 7),
('Centro Congressi Venezia', 8),
('Centro Congressi Verona',9),
('Palazzo dei Congressi Catania', 10),
('Centro Congressi Genova', 11),
('Centro Congressi Palermo',12 ),
('Fiera Congressi Rimini',13 ),
('Centro Congressi Bari',14 ),
('Centro Congressi Trieste',15 ),
('Centro Congressi Cagliari',16 ),
('Università degli Studi di Milano',17 ),
('Palazzo dei Congressi della Sapienza',18 ),
('Villa Erba',19 ),
('Centro Studi di Positano',20 ),
('Auditorium Parco della Musica',21 ),
('Castello di Rivoli',22 ),
('Villa Miani',23 ),
('Università di Bologna', 24),
('Accademia Nazionale dei Lincei',25 ),
('Villa Farnesina',26),
('Palazzo delle Esposizioni',27),
('Villa Mondragone',28),
('Università di Padova',29),
('Villa La Pietra',30 ),
('Fondazione Cini',31 ),
('Castello di Belgioioso',32 );

