SET search_path TO conference;
INSERT INTO sponsor (nome)
VALUES
('Apple Inc.'),
('Amazon.com Inc.'),
('Microsoft Corporation'),
('Alphabet Inc.'),
('Facebook Inc.'),
('Berkshire Hathaway Inc.'),
('Johnson & Johnson'),
('Visa Inc.'),
('Walmart Inc.'),
('JPMorgan Chase & Co.'),
('Procter & Gamble Co.'),
('Mastercard Incorporated'),
('UnitedHealth Group Incorporated'),
('Intel Corporation'),
('Verizon Communications Inc.'),
('Coca-Cola Company'),
('Cisco Systems Inc.'),
('AT&T Inc.'),
('Netflix Inc.'),
('Pfizer Inc.'),
('Comcast Corporation'),
('Nike Inc.'),
('Adobe Inc.'),
('Toyota Motor Corporation'),
('McDonald''s Corporation'),
('Merck & Co. Inc.'),
('Starbucks Corporation'),
('General Electric Company'),
('Oracle Corporation'),
('IBM Corporation'),
('Goldman Sachs Group Inc.'),
('3M Company'),
('Walgreens Boots Alliance Inc.'),
('Exxon Mobil Corporation'),
('American Express Company'),
('Chevron Corporation'),
('The Home Depot Inc.'),
('Caterpillar Inc.'),
('Salesforce.com Inc.'),
('The Walt Disney Company'),
('Target Corporation'),
('General Motors Company'),
('Delta Air Lines Inc.'),
('Lowe''s Companies Inc.'),
('Abbott Laboratories'),
('Honeywell International Inc.'),
('Costco Wholesale Corporation'),
('Colgate-Palmolive Company'),
('Accenture plc'),
('BMW AG'),
('Ford Motor Company'),
('SSC Napoli'),
('Tesla Inc.'),
('Space X'),
('Blue Origin LLC'),
('Virgin Galactic');