INSERT INTO sede (nome, via, civico, cap, city) VALUES
('Centro Congressi Roma', 'Via del Corso', '123', '00186', 'Roma'),
('Fiera Milano Congressi', 'Strada Statale Sempione', '28', '20017', 'Rho'),
('Centro Congressi Firenze', 'Piazza Santa Croce', '16', '50122', 'Firenze'),
('Palazzo dei Congressi', 'Viale della Fiera', '20', '44124', 'Ferrara'),
('Centro Congressi Napoli', 'Via Partenope', '1', '80121', 'Napoli'),
('Centro Congressi Bologna', 'Piazza Maggiore', '6', '40124', 'Bologna'),
('Centro Congressi Torino', 'Via Roma', '156', '10122', 'Torino'),
('Centro Congressi Venezia', 'Piazza San Marco', '1', '30124', 'Venezia'),
('Centro Congressi Verona', 'Corso Porta Nuova', '1', '37122', 'Verona'),
('Palazzo dei Congressi Catania', 'Via Vittorio Emanuele', '121', '95131', 'Catania'),
('Centro Congressi Genova', 'Via XX Settembre', '20', '16121', 'Genova'),
('Centro Congressi Palermo', 'Via Maqueda', '187', '90133', 'Palermo'),
('Fiera Congressi Rimini', 'Via della Fiera', '52', '47923', 'Rimini'),
('Centro Congressi Bari', 'Via Sparano', '120', '70121', 'Bari'),
('Centro Congressi Trieste', 'Piazza Unità d''Italia', '1', '34121', 'Trieste'),
('Centro Congressi Cagliari', 'Viale Trieste', '105', '09123', 'Cagliari'),
('Università degli Studi di Milano', 'Via Festa del Perdono', '7', '20122', 'Milano'),
('Palazzo dei Congressi della Sapienza', 'Piazzale Aldo Moro', '5', '00185', 'Roma'),
('Villa Erba', 'Largo Luchino Visconti', '4', '22012', 'Cernobbio'),
('Centro Studi di Positano', 'Via Pasitea', '346', '84017', 'Positano'),
('Auditorium Parco della Musica', 'Viale Pietro de Coubertin', '30', '00196', 'Roma'),
('Castello di Rivoli', 'Piazza Mafalda di Savoia', '10098', '10098', 'Rivoli'),
('Villa Miani', 'Via Trionfale', '151', '00136', 'Roma'),
('Università di Bologna', 'Via Zamboni', '33', '40126', 'Bologna'),
('Accademia Nazionale dei Lincei', 'Via della Lungara', '230', '00165', 'Roma'),
('Villa Farnesina', 'Via della Lungara', '230', '00165', 'Roma'),
('Palazzo delle Esposizioni', 'Via Nazionale', '194', '00184', 'Roma'),
('Villa Mondragone', 'Via Frascati', '51', '00040', 'Monte Porzio Catone'),
('Università di Padova', 'Via VIII Febbraio', '2', '35122', 'Padova'),
('Villa La Pietra', 'Via Bolognese', '120', '50139', 'Firenze'),
('Fondazione Cini', 'Isola di San Giorgio Maggiore', '30124', '30124', 'Venezia'),
('Castello di Belgioioso', 'Piazza Castello', '2', '27011', 'Belgioioso');